cozy/ACH

README.md, index.js, libs/ACH.js, libs/createFiles.js, package.json, yarn.lock
Usage example :  `yarn generateFiles / 1000` will spit out 1000 files at the root folder.
We need to do some perf work on drive and need LOADS of files quickly.
=> feat: add command to generate LOTS of files

index.js
If make-token failed, ACH export would crash. Here, if make-token fails,
the user is warned and execution continues with normal oauth flow.
=> 🐝 fix: Defensive programming if make-token fails

package.json
This is related to #2. I also removed the v1.0.0 tag, so semantic-release can take the power and do its job: releasing the v1.0.0 on npm.
=> chore: update name to cozy-ach

index.js, libs/exportData.js
The filename argument is now optional for the export command. If no filename is passed, output will be written to the console. This makes it easier to pipe the content of ACH into another program, for example `mint view`.
=> feat: Output export to stdout if no filename

libs/runBatch.js, scripts/api.js, scripts/deleteDuplicateBankAccountsWithNoOperations.js, scripts/deleteDuplicateBankAccountsWithNoOperations.spec.js
Since Cozy doctypes uses a global variable for its client, it cannot be used concurrently. Revert to the old method of using mkAPI.
See https://github.com/cozy/cozy-libs/pull/137
=> Do not use doctypes

libs/config.js
ACH would crash if the config file was not present. Now, it does
not crash. The `batch` command will not be able to work without config
file though.
=> fix: Do not crash if no config file

libs/importData.js
I did the following:
* `ACH export io.cozy.bank.groups` on an instance that have no accounts for this doctype
* `ACH import goups.json`
And I got the following error:
```console
Error: Error: Must pass data, you passed undefined
at importData (/home/drazik/.config/yarn/global/node_modules/cozy-ach/libs/importData.js:212:13)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:188:7)
```
So I changed a little bit the code so we don't totally crash when there is no doc for a given doctype, but print a message in the console and continue the process for the next doctype.
=> fix: Don't fail when there are no docs for a doctype

scripts/api.js, scripts/banking/mergeDuplicateBankAccounts.js, scripts/banking/mutations.js, scripts/banking/mutations.spec.js, scripts/banking/removeDuplicateTransactions.js
ACH script using the match-transaction logic from cozy-doctypes to remove duplicate transactions between BI and Linxo. Matching is done intra-day.
=> feat: Add removeDuplicateTransactions script

libs/utils.js, scripts/banking/bankTransactionsAccountsMigrationV1.js, scripts/banking/bankTransactionsCheckTinDate.js
Just moving the utils to be able to use them in contacts migration
=> refactor: Move diff and logWithInstance to libs/utils

scripts/contacts/migrateContactsV1toV2.js, scripts/contacts/migrateContactsV1toV2.spec.js
Avoid useless queries and possible `io.cozy.contacts.accounts` creation if there is no contact on the instance
=> Just display a log if there is no contacts to migrate

libs/api.js, libs/api.spec.js, scripts/contacts/migrateContactsV1toV2.js, scripts/contacts/migrateContactsV1toV2.spec.js
First, create a contact account for each gmail account seen in contacts metadata. Then, migrate contacts and link them to the correct contact account. We don't care about `io.cozy.accounts` anymore in this migration.
=> feat(contacts): Handle contacts from multiple google accounts

cli.js, libs/runBatch.js
Until now, `ACH batch` runs the script on 30 instances at the same time. However, we may want to use a smaller (or bigger) pool size depending on the script to avoid that the process uses too much resources.
This PR adds an option (`-p` or `--pool-size`) that allow users to control the number of concurrency runs of their script.
=> Add an option to control the pool size

libs/admin.js, libs/errors.js, libs/getClient.js, libs/getClient.spec.js, libs/runBatch.js, libs/runBatch.spec.js, package.json, yarn.lock
Instead of passing several arguments in the run() function, we receive one
context object containing :
- client: a new cozy-client
- dryRun: whether we've been run with the dryRun flag
- logger: a proxy for console methods that adds the domain of the current cozy
- stats: an object where to store useful statistics
Additionally, the `runBatch` now resolves with its results.
```
runBatch(...).then(({ results, stats }) => {
reportStats(stats)
reportResults(results)
})
```
The user is for now responsible to report the errors in the results. Errors
have the `error` attribute whereas normal results do not have it.
=> Context object for ACH batch

scripts/cleanNotExistingBillsInOperations.js, scripts/cleanNotExistingBillsInOperations.spec.js
This script finds bills and reimbursements in bank operations which do not exist anymore
If any and if not in dry run, their reference will be removed from operations
=> feat: in bank operations, remove references to removed bills

cli.js, libs/getHandlebarsOptions.js, libs/importData.js, libs/parseDataFile.js, libs/utils.js
When importing data using handlebars templates, we had errors like `SyntaxError: Unexpected token { in JSON at position 31` because we were trying to read the doctypes from the JSON file before transforming it.
=> fix: Import works with handlebars templates

libs/scripts.js
The `ls-scripts` command was broken because it was looking for scripts in `libs/scripts/` instead of `scripts/`. Furthermore, it didn't list the scripts in sub-directories, such as `banking` or `contacts`.
This PR fix the command and make it recursive to list all the scripts, even in sub-directories.
=> feat: Recursively list scripts files

libs/ACH.js, libs/runBatch.spec.js, package.json, yarn.lock
In the future, we expect to migrate everything on cozy-client. As a
starting point, we add this initialization so new scripts can use
cozy-client.
=> Initialize cozy-client

cli.js, libs/ACH.js
It is often the case when working with ACH that we copy/paste an URL
from the browser, from an app.
When this is the case the URL contains the app and ACH
did not handle this case. Now, ACH handles it gracefully and remove
the -<app> part if present.
Now we can do:
```
ach export --url https://mycozy-banks.mycozy.cloud io.cozy.contacts
```
=> feat: Process url CLI arg to remove -<app> if present

libs/utils.js
Fixes #84
The files were uploaded with parent folder's id as path. So they were
not in the directory they belong to, but in a directory located at the
root and named after the real file's parent directory id.
This is fixed by  giving the parent folder's path instead of id to the
`uploadFile` function.
=> fix: importDir uses the same structure as source directory

cli.js
url and token were not passed, making the command unusable
=> fix: Include url and token for generateFiles

cli.js, cli.spec.js
This PR fix a dirty bug experienced since few months with latest version.
The helper add by Patrick to remove apps prefix in url (home-toto.mycozy.cloud become toto.mycozy.cloud) do not work as expected. It add a slash at the end of the string (as an compliant url). 
This side effect broke the make-token command. 
This fix simply remove it and keep the helper.
=> fix: Remove the slash trailing at the end of domain (fix autoToken)

cli.js, libs/exportData.js
The limit option is not very helpful on the _all_docs route because the
documents are not sorted.
The `last` option allows to ask for the last x docs, sorted by
descending updated date
=> feat: Replace export limit by last

cli.js, cli.spec.js
cas problématique : instance en local (donc http et non https) et oublie de le spécifier dans l'url "toto.cozy.localhost:8080"
Dans ce cas il y a un message d'erreur de parsing, sans trop qu'on sache pourquoi si on ne lit pas le code
=> feat: ParseCozyURL throw error if url doesn't start with `http`

libs/ACH.js
Add a log to show how to pass a specific
URL to ACH. No need to scroll down the
README anymore. The answer is now right
in front of us.
=> feat: Add log to show --url

README.md, libs/ACH.js, libs/exportData.js, libs/getClient.js, libs/getClient.spec.js, package.json
On Windows OS, `/tmp/` folder does not exist and may be considered as
relative path
To fix this we want to use `os.tmpdir()` to point to the OS specified
path for temp files
This modification change the macOS behavior as the used folder for
storing token is not `/tmp/` anymore but
`/var/folders/<SOME_UNIQUE_PATH>/T/` which is the per-user temporary
folder (see https://magnusviri.com/what-is-var-folders.html)
Fixes: #74
---
This PR also adds some securities in code to check that folders exist
---
This PR also improves project documentation and tooling
=> Fix: Make ACH work on Windows

libs/ACH.js
When connecting to a local cozy-stack (i.e. `cozy.localhost:8080`), the user should configure their `hosts` file. Otherwise they will get an `getaddrinfo ENOTFOUND` error
People often get confused as their web browser success to access the local cozy-stack. But some web browsers have their internal domain resolution mechanism and so they may succeed to access the cozy-stack without the `hosts` entry. A terminal cannot do that
=> feat: Suggest adding domain to hosts file when connection fails

scripts/timeseries/removeAggregation.js
This is useful to test the aggregation service or to fix some mistakes.
Note the generic script parameter system seems rather fragile and is not really satisfying at this moment: any script called through `ACH script <path>` can get a `param`, which is an array of arguments passed to the script.
For example, by calling `ACH script timeseries/removeAggregations.js 2023-09-10`, the date will be in `params[0]`. But then, the caller of the script has no way to know this rather than reading the code...
=> feat: Add remove aggregation script

data/timeseries/geojson-01.js, data/timeseries/geojson-02.js, data/timeseries/geojson-03.js
Cette propriété existe sur les timeseries réelles et est égale au `io.cozy.accounts.auth.login`
=> feat: Add missing `captureDevice` property to timeseries fixtures
