cozy/ACH

- index.js
If the -t option is not passed and make-token is available, the
export command will automatically create a token.
> ✨ feat: if make-token is available, automatically creates token

- index.js
- libs/ACH.js
Ability to download a file from a cozy via ACH.
`ACH downloadFile <fileId>`
> feat: ability to download a file from a cozy

- libs/exportData.js
For large collection of documents (> 10000), query would timeout. When
exporting, we do not have to query, we can simply use the _all_docs route.
> perf: use all_docs API to be able to export large collections of docs

- data/bank/README.md
> chore: Update banks fixtures URL

- package.json
- scripts/fixAccounts.js
- scripts/fixAccounts.spec.js
- yarn.lock
~~Waiting for https://github.com/cozy/ACH/pull/19~~
This PR adds a fixAccounts script which:
* Fix legacy accounts with `dir_id` attribute
* Fix legacy accounts with `folderId` attribute
* Move `folderPath` attribute to `path.folderPath`
* Ensure consistency between `auth.folderPath` and `auth.namePath`
* Retrive destination folder information from related trigger.
> Add fixAccounts script

- scripts/fixAccounts.js
* Logs url on every account
* Catch TOS related error
* Prevent undefined account_type
* Avoid unecessary update for OAuth accounts
> Improve fixAccounts script

- scripts/resetFilesReferencedBy.js
- scripts/resetFilesReferencedBy.spec.js
This removes all the `referenced_by` contained into the files docs.
> feat: Add script for reset files references

- cli.js
- libs/mutations.js
- libs/mutations.spec.js
- scripts/banking/removeDuplicateTransactions.js
Three disconnected improvements
- Better display of removeDuplicateTransactions (add dates)
- Do not let async errors from main go uncatched
- Support mutations without both toDelete and toUpdate
> Improvements

- libs/api.js
- package.json
- scripts/contacts/migrateContactsV1toV2.js
- scripts/contacts/migrateContactsV1toV2.spec.js
- yarn.lock
- Create `io.cozy.contacts.account`
- Create cozyMetadata, add sync info
> Contacts migration v1 to v2

- libs/scripts.js
Don't hide the real error if there is an error during `requireScript`
> Display the real error message if there is an error while searching for script

- libs/exportData.js
> feat: Do not output error when db does not exist

- README.md
Copy pasted the output of ACH --help.
> docs: Update help

- cli.js
Import subcommand did not have autotoken.
> feat: auto-token for imports

- libs/importData.js
No need to output every id inserted in the db.
> feat: Import less verbose

- libs/admin.js
- libs/config.js
- libs/tasks.js
Add functions and tools for running tasks on several cozies.
The TaskRunner's goal is to be able to chain tasks that need to be parallelized over several cozies.
> feat: Admin tools

- cli.js
Generate a token for an arbitrary doctype list.
Should help with https://forum.cozy.io/t/app-de-gestion-des-cartes-fidelites/6766/3.
> feat: Ability to generate token for an arbitrary doctype

- README.md
Repository is the wrong word in this context.
> docs: Better readme for importDir

- README.md
- examples/data-from-csv/README.md
- examples/data-from-csv/accounts.csv
- examples/data-from-csv/operations.csv
- examples/data-from-csv/parser.js
- libs/tasks.js
- libs/utils.js
- scripts/banking/createAggregatorAccount.js
- scripts/fixAccounts.js
- scripts/fixAccounts.spec.js
- scripts/removeOldEdfBills.js
> docs: Add bit of doc to import a CSV

- cli.js
> fix: token command execution

- README.md
Just updated README.md with the output of ACH --help command
> fix: update README with the token command

- libs/importData.js
- libs/utils.js
> fix: better error message if the JWT token is expired

- libs/config.js
> feat: Ability to support custom domains via config file

- package.json
Semantic release fix with --pro option
> fix: Fix the semantic release publication with new address

- scripts/indexes/common.js
- scripts/indexes/copy-indexes.js
- scripts/indexes/create-and-query.js
This is useful for testing indexes behaviour, e.g. on creation, query
and copy.
> feat: Add indexes scripts

- cli.js
- libs/exportData.js
This might be useful when there are a lot of data to export and only few of them are necessary
> feat: Add limit option when exporting data

- cli.js
This allows to have tokens generated automatically via make-token
command when available
> feat: Add missing autotoken for delete and updateSettings command

- cli.js
- libs/ACH.js
- libs/exportData.js
This is useful to export a single doc  by its id
> feat: Add exportSingle command
